const lang = {
    en: {
        search: "Search",
        getSearchPlaceholder: "What would you like to watch today?",
        playing: "Now Playing Movies",
        rated: "Top Rated Movies",
        upcoming: "Upcoming Movies",
        popular: "Popular Movies",
        trendingMovie: "Trending Movies",
        trendingTv: "Trending TV Shows",
    },
    hindi: {
        search: "खोज",
        getSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
        playing: "अभी फिल्में चल रही हैं",
        rated: "शीर्ष रेटेड फिल्में",
        upcoming: "आने वाली फिल्में",
        popular: "लोकप्रिय फिल्में",
        trendingMovie: "ट्रेंडिंग फिल्में",
        trendingTv: "ट्रेंडिंग टीवी शो",
    },
    bhojpuri: {
        search: "खोजी",
        getSearchPlaceholder: "आज रउरा का देखल चाहब?",
        rated: "टॉप रेटेड फिलिमन के बा",
        playing: "अब सिनेमा चलत बा",
        upcoming: "आगामी फिल्मन",
        popular: "लोकप्रिय फिल्में",
        trendingMovie: "ट्रेंडिंग फिल्में",
        trendingTv: "ट्रेंडिंग टीवी शो",
    },
    bengali: {
        search: "অনুসন্ধান করুন",
        getSearchPlaceholder: "আপনি আজ কি দেখতে চান?",
        playing: "এখন সিনেমা চলছে",
        rated: "শীর্ষ রেটেড সিনেমা",
        upcoming: "আসন্ন সিনেমা",
        popular: "জনপ্রিয় সিনেমা",
        trendingMovie: "ট্রেন্ডিং সিনেমা",
        trendingTv: "ট্রেন্ডিং টিভি শো",
    },

    tamil: {
        search: "தேடு",
        getSearchPlaceholder: "இன்று நீங்கள் எதைப் பார்க்க விரும்புகிறீர்கள்?",
        playing: "இப்போது விளையாடும் திரைப்படங்கள்",
        rated: "சிறந்த தரமதிப்பீடு பெற்ற திரைப்படங்கள்",
        upcoming: "ஆரம்பிக்கப்போகும் படங்கள்",
        popular: "பிரபலமான திரைப்படங்கள்",
        trendingMovie: "புதிய திரைப்படங்கள்",
        trendingTv: "புதிய டிவி ஷோக்கு புதுசா சென்னல்",
    },
    telugu: {
        search: "వెతకండి",
        getSearchPlaceholder: "మీరు ఈరోజు ఏమి చూడాలనుకుంటున్నారు?",
        playing: "ఇప్పుడు సినిమాలు ప్లే అవుతున్నాయి",
        rated: "అగ్ర రేటింగ్ పొందిన సినిమాలు",
        upcoming: "రెడీ అయ్యే సినిమాలు",
        popular: "ప్రజాదరణం పొందిన సినిమాలు",
        trendingMovie: "ట్రెండింగ్ సినిమాలు",
        trendingTv: "ట్రెండింగ్ టీవీ షోలు",
    },
    malayalam: {
        search: "തിരയുക",
        getSearchPlaceholder: "ഇന്ന് നിങ്ങൾ എന്താണ് കാണാൻ ആഗ്രഹിക്കുന്നത്?",
        playing: "ഇപ്പോൾ സിനിമകൾ പ്ലേ ചെയ്യുന്നു",
        rated: "മികച്ച റേറ്റുചെയ്ത സിനിമകൾ",
        upcoming: "സൂചിപ്പിക്കപ്പെടുന്ന സിനിമകൾ",
        popular: "ജനപ്രിയമായ സിനിമകൾ",
        trendingMovie: "ട്രെന്ഡിം സിനിമകൾ",
        trendingTv: "ട്രെന്ഡിം ടിവി ഷോകൾ",
    },
    spanish: {
        search: "buscar",
        getSearchPlaceholder: "¿Qué te gustaría ver hoy?",
        playing: "Películas que se están reproduciendo ahora",
        rated: "Películas mejor valoradas",
        upcoming: "Próximas películas",
        popular: "Películas populares",
        trendingMovie: "Películas de tendencia",
        trendingTv: "Programas de televisión de tendencia",
    },
    french: {
        search: "Recherche",
        getSearchPlaceholder: "Qu’aimeriez-vous regarder aujourd’hui ?",
        playing: "Lecture de films en cours",
        rated: "Films les mieux notés",
        upcoming: "Prochaines sorties",
        popular: "Films populaires",
        trendingMovie: "Films tendance",
        trendingTv: "Émissions de télévision tendance",
    },
}

export default lang;
